name: Deploy mastering-react to GitHub Pages

on:
  push:
    branches: [ mastering-react ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mastering-react

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to folder inside gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: mastering-react/dist
          destination_dir: mastering-react
